/**
 * load-analysis.ts
 *
 * 構造物検出結果JSONをTypeScriptに読み込むローダー。
 * patent/data/structures/{slug}.json を動的にスキャンして読み込み、
 * diagram-generator.ts で SpotDiagramData に変換する。
 *
 * ビルド時（SSG/ISR）に実行される Server-side コード。
 */

import fs from "fs";
import path from "path";
import { generateDiagramData } from "./diagram-generator";
import type { SpotAnalysisResult } from "./types";
import type { SpotDiagramData } from "@/components/spots/fishing-point-diagram";

// ---------------------------------------------------------------------------
// 動的スキャンによる検出結果の読み込み
// patent/data/structures/ 配下の全JSONを自動読込
// ---------------------------------------------------------------------------

const STRUCTURES_DIR = path.join(
  process.cwd(),
  "patent",
  "data",
  "structures"
);

function loadAnalysisDataMap(): Record<string, SpotAnalysisResult> {
  const map: Record<string, SpotAnalysisResult> = {};

  if (!fs.existsSync(STRUCTURES_DIR)) {
    return map;
  }

  const files = fs.readdirSync(STRUCTURES_DIR).filter((f) => f.endsWith(".json"));

  for (const file of files) {
    try {
      const filePath = path.join(STRUCTURES_DIR, file);
      const raw = fs.readFileSync(filePath, "utf-8");
      const data = JSON.parse(raw) as SpotAnalysisResult;
      const slug = file.replace(/\.json$/, "");
      map[slug] = data;
    } catch {
      // JSONパースエラー時はスキップ
    }
  }

  return map;
}

// ビルド時に1回だけ読み込み（モジュールキャッシュ）
let _cachedMap: Record<string, SpotAnalysisResult> | null = null;

function getAnalysisDataMap(): Record<string, SpotAnalysisResult> {
  if (!_cachedMap) {
    _cachedMap = loadAnalysisDataMap();
  }
  return _cachedMap;
}

// ---------------------------------------------------------------------------
// API
// ---------------------------------------------------------------------------

/**
 * スポットslugから構造物解析結果を取得。
 * 解析結果が存在しない場合はnullを返す。
 */
export function getAnalysisResult(
  slug: string
): SpotAnalysisResult | null {
  return getAnalysisDataMap()[slug] ?? null;
}

/**
 * スポットslugから自動生成ダイアグラムデータを取得。
 * 特許パイプラインの最終出力: 検出結果 → ダイアグラムデータ。
 *
 * 1. 検出結果JSONを読み込み
 * 2. diagram-generator で SpotDiagramData に変換
 * 3. FishingPointDiagram コンポーネントに渡せる形式で返す
 */
export function getAutoGeneratedDiagram(
  slug: string
): SpotDiagramData | null {
  const analysis = getAnalysisResult(slug);
  if (!analysis) return null;

  return generateDiagramData(analysis);
}

/**
 * 自動生成ダイアグラムが利用可能なスポット一覧を返す。
 */
export function getAnalyzedSpotSlugs(): string[] {
  return Object.keys(getAnalysisDataMap());
}
