/**
 * load-analysis.ts
 *
 * 構造物検出結果JSONをTypeScriptに読み込むローダー。
 * patent/data/structures/{slug}.json を読み込み、
 * diagram-generator.ts で SpotDiagramData に変換する。
 *
 * ビルド時（SSG/ISR）に実行される Server-side コード。
 */

import { generateDiagramData } from "./diagram-generator";
import type { SpotAnalysisResult } from "./types";
import type { SpotDiagramData } from "@/components/spots/fishing-point-diagram";

// ---------------------------------------------------------------------------
// 静的インポートによる検出結果の読み込み
// (Next.js SSGで安全に動作するよう、JSONを直接importする)
// ---------------------------------------------------------------------------

import hiraiso from "../../../patent/data/structures/hiraiso-fishing-park.json";

/**
 * 利用可能な検出結果のマッピング。
 * 新しいスポットの検出結果が追加されたら、ここにimportを追加する。
 */
const analysisDataMap: Record<string, SpotAnalysisResult> = {
  "hiraiso-fishing-park": hiraiso as unknown as SpotAnalysisResult,
};

// ---------------------------------------------------------------------------
// API
// ---------------------------------------------------------------------------

/**
 * スポットslugから構造物解析結果を取得。
 * 解析結果が存在しない場合はnullを返す。
 */
export function getAnalysisResult(
  slug: string
): SpotAnalysisResult | null {
  return analysisDataMap[slug] ?? null;
}

/**
 * スポットslugから自動生成ダイアグラムデータを取得。
 * 特許パイプラインの最終出力: 検出結果 → ダイアグラムデータ。
 *
 * 1. 検出結果JSONを読み込み
 * 2. diagram-generator で SpotDiagramData に変換
 * 3. FishingPointDiagram コンポーネントに渡せる形式で返す
 */
export function getAutoGeneratedDiagram(
  slug: string
): SpotDiagramData | null {
  const analysis = getAnalysisResult(slug);
  if (!analysis) return null;

  return generateDiagramData(analysis);
}

/**
 * 自動生成ダイアグラムが利用可能なスポット一覧を返す。
 */
export function getAnalyzedSpotSlugs(): string[] {
  return Object.keys(analysisDataMap);
}
