import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/api/",
          "/_next/",
          "/shops/*/dashboard",
          "/spots/submit",
          "/spots/compare",
          "/favorites",
          "/login",
          "/mypage",
          "/*/opengraph-image",
        ],
      },
      { userAgent: "Googlebot", allow: "/" },
      { userAgent: "Mediapartners-Google", allow: "/" },
      { userAgent: "AdsBot-Google", allow: "/" },
      { userAgent: "Bingbot", allow: "/" },
      { userAgent: "Yandex", allow: "/" },
      { userAgent: "Baiduspider", allow: "/" },
      { userAgent: "Applebot", allow: "/" },
      { userAgent: "DuckDuckBot", allow: "/" },
      { userAgent: "GPTBot", disallow: "/" },
      { userAgent: "OAI-SearchBot", disallow: "/" },
      { userAgent: "ChatGPT-User", disallow: "/" },
      { userAgent: "Google-Extended", disallow: "/" },
      { userAgent: "PerplexityBot", disallow: "/" },
      { userAgent: "ClaudeBot", disallow: "/" },
      { userAgent: "anthropic-ai", disallow: "/" },
      { userAgent: "Claude-Web", disallow: "/" },
      { userAgent: "CCBot", disallow: "/" },
      { userAgent: "Applebot-Extended", disallow: "/" },
      { userAgent: "Bytespider", disallow: "/" },
      { userAgent: "cohere-ai", disallow: "/" },
      { userAgent: "Meta-ExternalAgent", disallow: "/" },
      { userAgent: "FacebookBot", disallow: "/" },
      { userAgent: "Amazonbot", disallow: "/" },
      { userAgent: "YouBot", disallow: "/" },
      { userAgent: "AI2Bot", disallow: "/" },
      { userAgent: "Timpibot", disallow: "/" },
      { userAgent: "ImagesiftBot", disallow: "/" },
      { userAgent: "Diffbot", disallow: "/" },
      { userAgent: "MicroAdBot", disallow: "/" },
      { userAgent: "SemrushBot", disallow: "/" },
      { userAgent: "AhrefsBot", disallow: "/" },
      { userAgent: "DotBot", disallow: "/" },
      { userAgent: "MJ12bot", disallow: "/" },
      { userAgent: "CriteoBot", disallow: "/" },
      { userAgent: "Sogou", disallow: "/" },
      { userAgent: "PetalBot", disallow: "/" },
    ],
    sitemap: [
      "https://tsurispot.com/sitemap.xml",
      "https://tsurispot.com/image-sitemap.xml",
    ],
    host: "https://tsurispot.com",
  };
}
