import type { Metadata } from "next";
import Link from "next/link";
import dynamic from "next/dynamic";
import { notFound } from "next/navigation";
import {
  Star,
  MapPin,
  Car,
  ChevronLeft,
  Fish,
  Compass,
  Wrench,
  Play,
  ExternalLink,
  Toilet,
  Store,
  ShoppingBag,
  MessageSquare,
  Shield,
  Navigation2,
  HelpCircle,
  BookOpen,
  Scale,
  FileText,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { fishingSpots, getSpotBySlug, getNearbySpots, getSpotsByPrefecture, type NearbySpot } from "@/lib/data/spots";
import { getNearbyShopsWithDistance } from "@/lib/data/shops";
import { getPrefectureByName } from "@/lib/data/prefectures";
import { SeasonCalendar } from "@/components/spots/season-calendar";
import { TackleCard } from "@/components/spots/tackle-card";
import { TideMazumeInfo } from "@/components/spots/tide-mazume-info";
import { FavoriteButton } from "@/components/spots/favorite-button";
import { GoTodayButton } from "@/components/spots/go-today-button";
import { GearGuideList } from "@/components/spots/gear-guide";
import { SafetyWarning } from "@/components/spots/safety-warning";
import { YouTubeVideoList } from "@/components/youtube-video-card";
import { YouTubeEmbedList } from "@/components/youtube-embed";
import { getVideosForMethods, getVideosForSpotType } from "@/lib/data/youtube-videos";
import {
  SPOT_TYPE_LABELS,
  DIFFICULTY_LABELS,
} from "@/types";
import { SpotImage } from "@/components/ui/spot-image";
import { SpotBouzuCard } from "@/components/spots/spot-bouzu-card";
import { Breadcrumb } from "@/components/ui/breadcrumb";
import { ShareButtons } from "@/components/ui/share-buttons";
import { InArticleAd } from "@/components/ads/ad-unit";
import { FishLikeButton } from "@/components/spots/fish-like-button";
import { FishingReportSummary } from "@/components/spots/fishing-report-summary";
import { SpotAffiliateRecommend } from "@/components/spots/spot-affiliate-recommend";
import { SpotDetailTabs } from "@/components/spots/spot-detail-tabs";
import { ParkingGuideCard, getParkingBadgeText, getParkingAmenityDescription, getParkingFaqAnswer } from "@/components/spots/parking-guide-card";
import { FamilyInfoCard } from "@/components/spots/family-info";
import { PackingChecklist } from "@/components/spots/packing-checklist";
import { getCatchReportsBySpot } from "@/lib/data/catch-reports";
import { CatchReportList } from "@/components/spots/catch-report-list";
import { CatchReportForm } from "@/components/spots/catch-report-form";
import { NearbyAccommodation } from "@/components/spots/nearby-accommodation";
import { SpotRulesCard } from "@/components/spots/spot-rules";
const SpotPhotoGallery = dynamic(
  () => import("@/components/spots/spot-photo-gallery").then(m => ({ default: m.SpotPhotoGallery })),
);
import { areaGuides } from "@/lib/data/area-guides";
import { explainTime, explainMethod } from "@/lib/fishing-term-helper";
import { seasonalGuides } from "@/lib/data/seasonal-guides";
import { FISHING_METHODS } from "@/lib/data/fishing-methods";
import { REGION_GROUPS } from "@/lib/data/regions-group";
import { getRelatedBlogPostsForSpot, BLOG_CATEGORIES } from "@/lib/data/blog";

import { RecentlyViewedTracker } from "@/components/spots/recently-viewed-tracker";
import { RecentlyViewedSpots } from "@/components/spots/recently-viewed";
import { CollapsibleSection } from "@/components/ui/collapsible-section";
import { PortMannerSection } from "@/components/spots/port-manner-section";
import { UmigyoBadge } from "@/components/spots/umigyo-badge";
import { umigyoDistricts } from "@/lib/data/umigyo";
import { getDiagramData } from "@/lib/data/fishing-points";
import { SatelliteAnalysisSection } from "@/components/patent/satellite-analysis-section";
import { enrichSpotWithStructures } from "@/lib/patent/derive-structure-types";
import { FishingPointDiagram } from "@/components/spots/fishing-point-diagram";
import { getAutoGeneratedDiagram } from "@/lib/patent/load-analysis";
import {
  generateSpotIntro,
  generateSpotTips,
  generateTimeAdvice,
  generateSeasonDetail,
  generateFacilityGuide,
  generateSpotSummary,
  generateContextMethodBrief,
  generateImprovedFAQs,
  generateAreaSeasonTrend,
} from "@/lib/utils/spot-content-generator";

// Below-the-fold client components loaded lazily
const StreetViewSection = dynamic(() => import("@/components/spots/street-view-section").then((m) => m.StreetViewSection), {
  loading: () => (
    <div className="space-y-3">
      <div className="h-5 w-36 animate-pulse rounded bg-muted" />
      <div className="h-64 w-full animate-pulse rounded-xl bg-muted" />
    </div>
  ),
});
const SpotWeatherTide = dynamic(() => import("@/components/spots/spot-weather-tide").then((m) => m.SpotWeatherTide), {
  loading: () => <div className="h-48 w-full animate-pulse rounded-xl bg-muted" />,
});
const CrowdPredictionCard = dynamic(() => import("@/components/spots/crowd-prediction").then((m) => m.CrowdPredictionCard), {
  loading: () => <div className="h-40 w-full animate-pulse rounded-xl bg-muted" />,
});
const NearbyGpsSearch = dynamic(() => import("@/components/spots/nearby-gps-search").then((m) => m.NearbyGpsSearch), {
  loading: () => <div className="h-32 w-full animate-pulse rounded-xl bg-muted" />,
});

type PageProps = {
  params: Promise<{ slug: string }>;
};

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const spot = getSpotBySlug(slug);
  if (!spot) return { title: "スポットが見つかりません" };

  const fishNames = spot.catchableFish.map((cf) => cf.fish.name).join("・");
  const topFishNames = spot.catchableFish.slice(0, 2).map((cf) => cf.fish.name).join("・");
  const top3FishNames = spot.catchableFish.slice(0, 3).map((cf) => cf.fish.name).join("・");
  const topMethodLabel = spot.catchableFish[0]?.method ?? "";
  const baseTitleText = `${spot.name}の釣り情報・釣果・アクセス`;
  const fullTitle = topMethodLabel && topFishNames
    ? `${baseTitleText}【${topMethodLabel}で${topFishNames}】`
    : baseTitleText;
  const title = fullTitle.length <= 60 ? fullTitle : baseTitleText;
  const isFamilyFriendly = spot.difficulty === "beginner" && spot.hasToilet && spot.hasParking;
  const popularityLabel = spot.rating >= 4.0 ? "人気" : spot.rating <= 3.0 ? "穴場" : "";
  const descParts: string[] = [
    `${spot.name}は${spot.region.prefecture}${spot.region.areaName}の${SPOT_TYPE_LABELS[spot.spotType]}。`,
    top3FishNames ? `${top3FishNames}が狙える${popularityLabel ? popularityLabel + "の" : ""}釣り場。` : "",
    spot.difficulty === "beginner" ? "初心者向け。" : "",
    spot.hasParking ? "駐車場あり。" : "",
    spot.hasToilet ? "トイレあり。" : "",
    spot.isFree ? "無料。" : "",
    isFamilyFriendly ? "ファミリーOK。" : "",
    "アクセス・仕掛け・釣果を完全ガイド。",
  ];
  const description = descParts.filter(Boolean).join("").slice(0, 155);
  const ogDescription = `${spot.name}（${spot.region.prefecture}${spot.region.areaName}）で${fishNames}が狙えます。${spot.description}`;

  // AdSense対策: 低品質スポットにnoindexを付与
  const descLength = (spot.description || "").length;
  const fishCount = spot.catchableFish.length;
  const isLowQuality = descLength < 100 || fishCount <= 2;

  return {
    title,
    description: description.slice(0, 160),
    keywords: [spot.name, spot.region.prefecture, spot.region.areaName, "釣り場", "釣りスポット", ...spot.catchableFish.slice(0, 5).map((cf) => cf.fish.name)],
    ...(isLowQuality && {
      robots: { index: false, follow: true },
    }),
    openGraph: {
      title: `${spot.name}の釣り情報・釣果・アクセス`,
      description: ogDescription.slice(0, 120),
      type: "article",
      url: `https://tsurispot.com/spots/${spot.slug}`,
      siteName: "ツリスポ",
    },
    twitter: {
      card: "summary_large_image",
      title: `${spot.name}の釣り情報`,
      description: ogDescription.slice(0, 120),
    },
    alternates: {
      canonical: `https://tsurispot.com/spots/${spot.slug}`,
    },
  };
}

export const dynamicParams = false;

export function generateStaticParams() {
  // 全スポットをSSGで事前生成（standalone出力ではISRが動かないため）
  return fishingSpots.map((spot) => ({ slug: spot.slug }));
}

export default async function SpotDetailPage({ params }: PageProps) {
  const { slug } = await params;
  const rawSpot = getSpotBySlug(slug);
  if (!rawSpot) notFound();
  const spot = enrichSpotWithStructures(rawSpot);
  // 特許パイプライン: 自動生成ダイアグラム優先、なければ手動データにフォールバック
  const autoGeneratedDiagram = getAutoGeneratedDiagram(slug);
  const manualDiagram = getDiagramData(slug);
  const fishingPoints = autoGeneratedDiagram ?? manualDiagram;

  // 今月釣れる魚を算出（Event schema用）
  const currentMonth = new Date().getMonth() + 1; // 1-12
  const monthNames = ["", "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"];
  const currentMonthFish = spot.catchableFish.filter((cf) => {
    if (cf.monthStart <= cf.monthEnd) {
      return currentMonth >= cf.monthStart && currentMonth <= cf.monthEnd;
    }
    // 年をまたぐ場合（例: 11月〜3月）
    return currentMonth >= cf.monthStart || currentMonth <= cf.monthEnd;
  });

  const currentYear = new Date().getFullYear();
  const nextMonth = currentMonth === 12 ? 1 : currentMonth + 1;
  const eventStartDate = `${currentYear}-${String(currentMonth).padStart(2, "0")}-01`;
  const eventEndYear = currentMonth === 12 ? currentYear + 1 : currentYear;
  const eventEndDate = `${eventEndYear}-${String(nextMonth).padStart(2, "0")}-01`;

  // TouristAttraction（観光地情報。aggregateRatingはGoogleが非対応なので含めない）
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "TouristAttraction",
    name: spot.name,
    description: spot.description,
    url: `https://tsurispot.com/spots/${spot.slug}`,
    address: {
      "@type": "PostalAddress",
      addressLocality: spot.region.areaName,
      addressRegion: spot.region.prefecture,
      addressCountry: "JP",
      streetAddress: spot.address,
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: spot.latitude,
      longitude: spot.longitude,
    },
    containedInPlace: {
      "@type": "Place",
      name: `${spot.region.prefecture}${spot.region.areaName}`,
      address: {
        "@type": "PostalAddress",
        addressLocality: spot.region.areaName,
        addressRegion: spot.region.prefecture,
        addressCountry: "JP",
      },
    },
    hasMap: `https://www.google.com/maps?q=${spot.latitude},${spot.longitude}`,
    isAccessibleForFree: spot.isFree,
    publicAccess: true,
    image: `https://tsurispot.com/api/og?title=${encodeURIComponent(spot.name)}&emoji=${encodeURIComponent("🎣")}`,
    amenityFeature: [
      ...(spot.hasParking ? [{ "@type": "LocationFeatureSpecification", name: "駐車場", value: true, description: getParkingAmenityDescription(spot.hasParking, spot.parkingDetail, spot.parkingGuide) }] : []),
      ...(spot.hasToilet ? [{ "@type": "LocationFeatureSpecification", name: "トイレ", value: true }] : []),
      ...(spot.hasRentalRod ? [{ "@type": "LocationFeatureSpecification", name: "レンタル竿", value: true }] : []),
      ...(spot.hasFishingShop ? [{ "@type": "LocationFeatureSpecification", name: "釣具店", value: true }] : []),
    ],
    touristType: spot.difficulty === "beginner" ? "初心者" : spot.difficulty === "intermediate" ? "中級者" : "上級者",
    speakable: {
      "@type": "SpeakableSpecification",
      cssSelector: ["h1", ".spot-description", ".catchable-fish-summary"],
    },
    ...(currentMonthFish.length > 0
      ? {
          event: {
            "@type": "Event",
            name: `${spot.name}｜${monthNames[currentMonth]}の釣りシーズン`,
            description: `${monthNames[currentMonth]}に${spot.name}で狙える魚: ${currentMonthFish.map((cf) => cf.fish.name).join("、")}`,
            startDate: eventStartDate,
            endDate: eventEndDate,
            eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
            eventStatus: "https://schema.org/EventScheduled",
            location: {
              "@type": "Place",
              name: spot.name,
              address: spot.address,
              geo: {
                "@type": "GeoCoordinates",
                latitude: spot.latitude,
                longitude: spot.longitude,
              },
            },
            organizer: {
              "@type": "Organization",
              name: "ツリスポ",
              url: "https://tsurispot.com",
            },
            ...(spot.isFree
              ? {
                  offers: {
                    "@type": "Offer",
                    price: "0",
                    priceCurrency: "JPY",
                    availability: "https://schema.org/InStock",
                  },
                }
              : {}),
          },
        }
      : {}),
  };

  // LocalBusiness（Googleが aggregateRating をサポートするタイプ）
  const localBusinessJsonLd = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    additionalType: "https://schema.org/SportsActivityLocation",
    name: spot.name,
    description: spot.description,
    url: `https://tsurispot.com/spots/${spot.slug}`,
    address: {
      "@type": "PostalAddress",
      addressLocality: spot.region.areaName,
      addressRegion: spot.region.prefecture,
      addressCountry: "JP",
      streetAddress: spot.address,
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: spot.latitude,
      longitude: spot.longitude,
    },
    hasMap: `https://www.google.com/maps?q=${spot.latitude},${spot.longitude}`,
    image: `https://tsurispot.com/api/og?title=${encodeURIComponent(spot.name)}&emoji=${encodeURIComponent("🎣")}`,
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: (spot.googleRating || spot.rating).toFixed(1),
      bestRating: "5",
      worstRating: "1",
      ratingCount: spot.googleReviewCount || (spot.reviewCount > 0 ? spot.reviewCount : 1),
    },
    ...(spot.officialUrl ? { sameAs: spot.officialUrl } : {}),
  };

  const prefForBreadcrumb = getPrefectureByName(spot.region.prefecture);
  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "ホーム",
        item: "https://tsurispot.com",
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "釣りスポット一覧",
        item: "https://tsurispot.com/spots",
      },
      ...(prefForBreadcrumb ? [{
        "@type": "ListItem",
        position: 3,
        name: spot.region.prefecture,
        item: `https://tsurispot.com/prefecture/${prefForBreadcrumb.slug}`,
      }] : []),
      {
        "@type": "ListItem",
        position: prefForBreadcrumb ? 4 : 3,
        name: spot.region.areaName,
        item: `https://tsurispot.com/area/${spot.region.slug}`,
      },
      {
        "@type": "ListItem",
        position: prefForBreadcrumb ? 5 : 4,
        name: spot.name,
        item: `https://tsurispot.com/spots/${spot.slug}`,
      },
    ],
  };

  const fishNames = spot.catchableFish.map((cf) => cf.fish.name).join("、");
  const difficultyAnswer =
    spot.difficulty === "beginner"
      ? `${spot.name}は初心者向けの釣り場です。足場が安定しており、安心して釣りを楽しめます。`
      : spot.difficulty === "intermediate"
        ? `${spot.name}は中級者向けの釣り場です。基本的な釣りの経験がある方におすすめです。`
        : `${spot.name}は上級者向けの釣り場です。十分な経験と装備が必要です。`;

  // 改善版FAQ（スポット固有の実用的アドバイス付き）
  const improvedFaqs = generateImprovedFAQs(spot);
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: improvedFaqs.map(faq => ({
      "@type": "Question" as const,
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer" as const,
        text: faq.answer,
      },
    })),
  };

  const spotSpeakableJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: `${spot.name}の釣り情報`,
    url: `https://tsurispot.com/spots/${spot.slug}`,
    speakable: {
      "@type": "SpeakableSpecification",
      cssSelector: ["h1", ".spot-description", ".catchable-fish-summary"],
    },
  };

  // VideoObject JSON-LD（YouTube動画の構造化データ）
  const spotMethods = spot.catchableFish.map((cf) => cf.method);
  const spotMethodVideos = spotMethods.length > 0
    ? getVideosForMethods(spotMethods, 2)
    : getVideosForSpotType(spot.spotType, 2);
  const videoJsonLd = spotMethodVideos.map(video => ({
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: video.title,
    description: `${spot.name}で使える釣り方の解説動画`,
    thumbnailUrl: `https://i.ytimg.com/vi/${video.videoId}/hqdefault.jpg`,
    uploadDate: "2025-01-01",
    contentUrl: `https://www.youtube.com/watch?v=${video.videoId}`,
    embedUrl: `https://www.youtube.com/embed/${video.videoId}`,
  }));

  // 夜釣り可能かどうかの判定（catchableFishのrecommendedTimeに「夜」を含む場合）
  const isNightFishing =
    spot.catchableFish.some((cf) => cf.recommendedTime.includes("夜"));

  // Single getNearbySpots call for both internal links and GPS search
  const allNearby: NearbySpot[] = getNearbySpots(spot.latitude, spot.longitude, 21)
    .filter((s) => s.id !== spot.id);

  // Top 5 for internal linking — 必要フィールドのみ抽出（RSCペイロード軽量化）
  const nearbySpots = allNearby.slice(0, 5).map((s) => ({
    id: s.id,
    slug: s.slug,
    name: s.name,
    spotType: s.spotType,
    distanceKm: s.distanceKm,
    prefecture: s.region.prefecture,
    fishNames: s.catchableFish.slice(0, 3).map((cf) => cf.fish.name),
  }));

  // Up to 20 for GPS search (client component) - lightweight data only
  const gpsNearbyData = allNearby.slice(0, 20).map((s) => ({
    slug: s.slug,
    name: s.name,
    spotType: s.spotType,
    latitude: s.latitude,
    longitude: s.longitude,
    prefecture: s.region.prefecture,
  }));

  // 海業地区マッチング
  const umigyoMatch = umigyoDistricts.find(
    (d) => d.prefecture === spot.region.prefecture &&
    (spot.name.includes(d.portName.replace(/漁港|港|地区/g, '')) ||
     d.portName.includes(spot.name.replace(/漁港|港/g, '')))
  );

  // 県内スポット数（信頼性指標用）
  const prefSpotCount = fishingSpots.filter((s) => s.region.prefecture === spot.region.prefecture).length;

  // Get nearby tackle shops (distance-based, within 50km)
  const nearbyShopsWithDist = getNearbyShopsWithDistance(spot.latitude, spot.longitude, 5, 50);

  return (
    <div className="container mx-auto px-4 py-6 sm:py-8">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(spotSpeakableJsonLd) }}
      />
      {videoJsonLd.map((vld, i) => (
        <script
          key={`video-${i}`}
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(vld) }}
        />
      ))}
      {/* 最近見たスポット記録 */}
      <RecentlyViewedTracker spot={{ slug: spot.slug, name: spot.name, prefecture: spot.region.prefecture, areaName: spot.region.areaName, spotType: spot.spotType }} />

      {/* パンくず */}
      <Breadcrumb
        items={[
          { label: "ホーム", href: "/" },
          { label: "釣りスポット", href: "/spots" },
          ...((() => {
            const pref = getPrefectureByName(spot.region.prefecture);
            return pref ? [{ label: spot.region.prefecture, href: `/prefecture/${pref.slug}` }] : [];
          })()),
          { label: spot.region.areaName, href: `/area/${spot.region.slug}` },
          { label: spot.name },
        ]}
      />

      {/* Back link */}
      <Link
        href="/spots"
        className="mb-4 inline-flex items-center gap-1 py-2 text-sm text-muted-foreground hover:text-foreground min-h-[44px]"
      >
        <ChevronLeft className="size-4" />
        スポット一覧に戻る
      </Link>

      {/* Header section - モバイルファースト設計 */}
      <div className="mb-5 sm:mb-6">
        {/* スポット名 + お気に入り（最上段） */}
        <div className="flex items-start justify-between gap-3">
          <h1 className="min-w-0 text-xl font-bold leading-tight text-pretty sm:text-2xl md:text-3xl">{spot.name}</h1>
          <FavoriteButton spotSlug={spot.slug} />
        </div>

        {/* 評価 + エリア情報 */}
        <div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-muted-foreground">
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-1">
              <Star className="size-4 fill-yellow-400 text-yellow-400" />
              <span className="font-medium text-foreground">
                {spot.rating.toFixed(1)}
              </span>
            </div>
            {spot.googleRating && (
              <div className="flex items-center gap-1 text-xs text-muted-foreground">
                <span className="text-[10px]">|</span>
                <svg viewBox="0 0 24 24" className="size-3.5" aria-hidden="true">
                  <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.06 5.06 0 0 1-2.2 3.32v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.1z"/>
                  <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
                  <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
                  <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
                </svg>
                <span>{spot.googleRating.toFixed(1)}</span>
                {spot.googleReviewCount && (
                  <span>({spot.googleReviewCount.toLocaleString()}件)</span>
                )}
              </div>
            )}
          </div>
          <div className="flex items-center gap-1">
            <MapPin className="size-4" />
            {(() => {
              const pref = getPrefectureByName(spot.region.prefecture);
              return (
                <>
                  {pref ? (
                    <Link href={`/prefecture/${pref.slug}`} className="hover:text-foreground hover:underline">
                      {spot.region.prefecture}
                    </Link>
                  ) : (
                    <span>{spot.region.prefecture}</span>
                  )}
                  {" "}
                  <Link href={`/area/${spot.region.slug}`} className="hover:text-foreground hover:underline">
                    {spot.region.areaName}
                  </Link>
                </>
              );
            })()}
          </div>
        </div>

        {/* バッジ（3段目） */}
        <div className="mt-2 flex flex-wrap gap-1.5">
          {spot.difficulty === "beginner" && (
            <Badge className="bg-green-600 hover:bg-green-600 text-xs">
              初心者OK
            </Badge>
          )}
          {spot.hasRentalRod && (
            <Badge className="bg-purple-600 hover:bg-purple-600 text-xs">
              手ぶらOK
            </Badge>
          )}
          {spot.isFree && (
            <Badge className="bg-orange-500 hover:bg-orange-500 text-xs">無料</Badge>
          )}
          <Badge variant="outline" className="text-xs">
            {SPOT_TYPE_LABELS[spot.spotType]}
          </Badge>
          {umigyoMatch && (
            <UmigyoBadge
              isModelDistrict={umigyoMatch.isModelDistrict}
              portName={umigyoMatch.portName}
            />
          )}
        </div>

        {/* 説明文（スポット固有の導入文） */}
        <div className="mt-3 space-y-3 text-sm leading-relaxed text-muted-foreground">
          <p>{spot.description}</p>
          <p className="border-t border-border/30 pt-3">{generateSpotIntro(spot)}</p>
        </div>

        {/* データ信頼性指標 */}
        <div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-1 rounded-lg border bg-muted/30 px-3 py-2 text-xs text-muted-foreground">
          <span className="flex items-center gap-1">
            <Fish className="size-3.5 text-primary" />
            釣れる魚 {spot.catchableFish.length}種類
          </span>
        </div>

        {/* 「今日行く」ボタン + ナビゲーション */}
        <div className="mt-4 rounded-xl border bg-muted/30 p-3 sm:p-4">
          <GoTodayButton slug={spot.slug} spotName={spot.name} />
          <div className="mt-3 flex gap-2">
            <a
              href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(spot.name)}`}
              target="_blank"
              rel="noopener noreferrer"
              className="flex-1 inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm transition-colors hover:bg-blue-700"
            >
              <MapPin className="size-4" />
              Google Mapで見る
            </a>
            <a
              href={`https://www.google.com/maps/dir/?api=1&destination=${spot.latitude},${spot.longitude}`}
              target="_blank"
              rel="noopener noreferrer"
              className="flex-1 inline-flex items-center justify-center gap-2 rounded-lg border-2 border-blue-600 px-4 py-2.5 text-sm font-bold text-blue-700 transition-colors hover:bg-blue-50"
            >
              <Navigation2 className="size-4" />
              ナビで行く
            </a>
          </div>
          <p className="mt-2 text-center text-[11px] text-muted-foreground">
            GPS座標で案内するので確実にたどり着けます
          </p>
        </div>

        {/* シェアボタン */}
        <div className="mt-3">
          <ShareButtons
            url={`https://tsurispot.com/spots/${spot.slug}`}
            title={`${spot.name}の釣り情報｜ツリスポ`}
          />
        </div>
      </div>

      {/* スポット写真ギャラリー（航空写真マップ or ユーザー投稿写真） */}
      <section className="mb-6 sm:mb-8">
        <SpotPhotoGallery photos={spot.spotPhotos} spotType={spot.spotType} spotName={spot.name} latitude={spot.latitude} longitude={spot.longitude} />
        {fishingPoints && (
          <div className="mt-4">
            <h3 className="mb-3 text-lg font-bold">魚礁図・ポイント図</h3>
            {autoGeneratedDiagram && (
              <p className="mb-2 text-xs text-indigo-600 font-medium">
                AI構造物解析により自動生成（特許技術）
              </p>
            )}
            <FishingPointDiagram spotName={spot.name} data={fishingPoints} />
          </div>
        )}
      </section>

      {/* 安全警告 */}
      {(spot.safetyLevel === "caution" || spot.safetyLevel === "danger") && (
        <div className="mb-4"><SafetyWarning level={spot.safetyLevel} notes={spot.safetyNotes} isKuchikomi={spot.isKuchikomiSpot} /></div>
      )}
      {spot.isKuchikomiSpot && spot.safetyLevel === "safe" && (
        <div className="mb-4"><SafetyWarning level="safe" notes={spot.safetyNotes} isKuchikomi={true} /></div>
      )}

      {/* タブレイアウト */}
      <SpotDetailTabs
        overviewTab={<>
          <h2 className="sr-only">{spot.name}の基本情報・設備</h2>
          <section>
            <h3 className="mb-4 text-lg font-bold">基本情報</h3>
            <Card className="py-4"><CardContent className="px-4">
              <dl className="space-y-3 text-sm">
                <div className="flex gap-4"><dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">住所</dt><dd><span className="font-medium">{spot.address}</span><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(spot.name)}`} target="_blank" rel="noopener noreferrer" className="ml-2 inline-flex items-center gap-1 text-xs text-blue-600 hover:underline"><MapPin className="size-3" />地図</a></dd></div>
                {spot.feeDetail && (<div className="flex gap-4"><dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">料金</dt><dd>{spot.feeDetail}</dd></div>)}
                {spot.isFree && (<div className="flex gap-4"><dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">料金</dt><dd className="font-medium text-orange-600">無料</dd></div>)}
                <div className="flex gap-4"><dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">難易度</dt><dd>{DIFFICULTY_LABELS[spot.difficulty]}</dd></div>
                <div className="flex gap-4"><dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">タイプ</dt><dd>{SPOT_TYPE_LABELS[spot.spotType]}</dd></div>
                {spot.rentalDetail && (<div className="flex gap-4"><dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">レンタル</dt><dd>{spot.rentalDetail}</dd></div>)}
                {spot.officialUrl && (<div className="flex gap-4"><dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">公式サイト</dt><dd><a href={spot.officialUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-blue-600 hover:underline"><ExternalLink className="size-3" />公式サイトを見る</a></dd></div>)}
              </dl>
            </CardContent></Card>
          </section>
          {/* 管理・問い合わせ情報 */}
          {spot.managementInfo && (
            <section className="mt-6">
              <h3 className="mb-4 text-lg font-bold">管理・問い合わせ</h3>
              <Card className="py-4"><CardContent className="px-4">
                <dl className="space-y-3 text-sm">
                  <div className="flex gap-4">
                    <dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">管理団体</dt>
                    <dd className="font-medium">{spot.managementInfo.organizationName}</dd>
                  </div>
                  {spot.managementInfo.contactPhone && (
                    <div className="flex gap-4">
                      <dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">電話</dt>
                      <dd><a href={`tel:${spot.managementInfo.contactPhone}`} className="text-blue-600 hover:underline">{spot.managementInfo.contactPhone}</a></dd>
                    </div>
                  )}
                  {spot.managementInfo.contactUrl && (
                    <div className="flex gap-4">
                      <dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">公式サイト</dt>
                      <dd><a href={spot.managementInfo.contactUrl} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">公式サイトを見る</a></dd>
                    </div>
                  )}
                  {spot.managementInfo.openingHours && (
                    <div className="flex gap-4">
                      <dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">営業時間</dt>
                      <dd>{spot.managementInfo.openingHours}</dd>
                    </div>
                  )}
                  {spot.managementInfo.closedDays && (
                    <div className="flex gap-4">
                      <dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">定休日</dt>
                      <dd>{spot.managementInfo.closedDays}</dd>
                    </div>
                  )}
                  {spot.managementInfo.fishingFee && (
                    <div className="flex gap-4">
                      <dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">釣り料金</dt>
                      <dd>{spot.managementInfo.fishingFee}</dd>
                    </div>
                  )}
                  {spot.managementInfo.licensingInfo && (
                    <div className="flex gap-4">
                      <dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">遊漁券</dt>
                      <dd>{spot.managementInfo.licensingInfo}</dd>
                    </div>
                  )}
                  {spot.managementInfo.notes && spot.managementInfo.notes.length > 0 && (
                    <div className="flex gap-4">
                      <dt className="w-20 shrink-0 font-medium text-muted-foreground sm:w-24">備考</dt>
                      <dd>
                        <ul className="list-disc pl-4 space-y-1">
                          {spot.managementInfo.notes.map((note, i) => (
                            <li key={i}>{note}</li>
                          ))}
                        </ul>
                      </dd>
                    </div>
                  )}
                </dl>
              </CardContent></Card>
            </section>
          )}
          {/* 釣りポイント配置図は「釣り場の様子」セクションに統合済み */}
          <section>
            <h3 className="mb-3 text-lg font-bold">設備</h3>
            <div className="flex flex-wrap gap-2">
              {spot.hasParking && <Badge variant="outline" className="text-xs"><Car className="size-3.5 mr-1" />{getParkingBadgeText(spot.hasParking, spot.parkingDetail, spot.parkingGuide)}</Badge>}
              {spot.hasToilet && <Badge variant="outline" className="text-xs"><Toilet className="size-3.5 mr-1" />トイレ</Badge>}
              {spot.hasFishingShop && <Badge variant="outline" className="text-xs"><Store className="size-3.5 mr-1" />釣具店</Badge>}
              {spot.hasRentalRod && <Badge variant="outline" className="text-xs"><Wrench className="size-3.5 mr-1" />レンタル竿</Badge>}
              {spot.hasConvenienceStore && <Badge variant="outline" className="text-xs"><ShoppingBag className="size-3.5 mr-1" />コンビニ近く</Badge>}
            </div>
          </section>
          {/* 釣りルール: 個別データがあるスポットのみ表示（推測ルールは誤情報の原因になるため非表示） */}
          {spot.rules && (
          <section>
            <h3 className="mb-3 flex items-center gap-2 text-lg font-bold"><Shield className="size-5" />釣りルール・禁止事項</h3>
            <SpotRulesCard rules={spot.rules} spotType={spot.spotType} spotName={spot.name} />
          </section>
          )}
          {spot.spotType === "port" && <PortMannerSection />}
          <section>
            <h3 className="mb-3 flex items-center gap-2 text-lg font-bold"><MessageSquare className="size-5" />みんなの釣果報告</h3>
            <CatchReportList spotSlug={slug} initialReports={getCatchReportsBySpot(slug)} />
            <CatchReportForm spotSlug={slug} spotName={spot.name} catchableFishNames={[...new Set(spot.catchableFish.map((cf) => cf.fish.name))]} />
            {/* エリアの釣果傾向（釣果報告の補完情報） */}
            {(() => {
              const areaTrend = generateAreaSeasonTrend(spot, fishingSpots);
              if (areaTrend.length === 0) return null;
              const currentMonthName = new Date().toLocaleDateString("ja-JP", { month: "long" });
              return (
                <div className="mt-4 rounded-lg border bg-muted/30 p-4">
                  <h4 className="mb-2 text-sm font-bold text-muted-foreground">
                    {spot.region.areaName}エリアの{currentMonthName}の釣果傾向
                  </h4>
                  <div className="flex flex-wrap gap-2">
                    {areaTrend.map(t => (
                      <span key={t.fishName} className="inline-flex items-center gap-1 rounded-full bg-background px-2.5 py-1 text-xs">
                        <Fish className="size-3 text-primary" />
                        {t.fishName}（{t.method}）
                      </span>
                    ))}
                  </div>
                  <p className="mt-2 text-xs text-muted-foreground">
                    ※ {spot.region.areaName}エリア内の他スポットのデータに基づく傾向です
                  </p>
                </div>
              );
            })()}
          </section>
          <section>
            <h3 className="mb-3 text-lg font-bold">混雑予想</h3>
            <CrowdPredictionCard rating={spot.rating} isFree={spot.isFree} difficulty={spot.difficulty} prefecture={spot.region.prefecture} hasParking={spot.hasParking} reviewCount={spot.reviewCount} />
          </section>
          {/* ファミリー向け情報: トイレ・駐車場あり＋初心者向けの場合のみ表示 */}
          {spot.hasToilet && spot.hasParking && spot.difficulty === "beginner" && (
          <section>
            <h3 className="mb-3 text-lg font-bold">ファミリー向け情報</h3>
            <FamilyInfoCard familyInfo={spot.familyInfo} spotType={spot.spotType} hasToilet={spot.hasToilet} hasParking={spot.hasParking} difficulty={spot.difficulty} />
          </section>
          )}
          <section>
            <h3 className="mb-3 text-lg font-bold">天気・潮汐情報</h3>
            <SpotWeatherTide lat={spot.latitude} lng={spot.longitude} spotName={spot.name} />
          </section>
          {/* LINE エリア釣果速報バナー */}
          <a
            href="https://line.me/R/ti/p/@710bvaxa"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-3 rounded-xl border border-[#06c755]/30 bg-[#06c755]/5 px-4 py-3 transition-colors hover:bg-[#06c755]/10"
          >
            <svg viewBox="0 0 24 24" fill="#06c755" className="h-8 w-8 flex-shrink-0" aria-hidden="true">
              <path d="M19.365 9.863c.349 0 .63.285.63.631 0 .345-.281.63-.63.63H17.61v1.125h1.755c.349 0 .63.283.63.63 0 .344-.281.629-.63.629h-2.386c-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.627-.63h2.386c.349 0 .63.285.63.63 0 .349-.281.63-.63.63H17.61v1.125h1.755zm-3.855 3.016c0 .27-.174.51-.432.596-.064.021-.133.031-.199.031-.211 0-.391-.09-.51-.25l-2.443-3.317v2.94c0 .344-.279.629-.631.629-.346 0-.626-.285-.626-.629V8.108c0-.271.173-.51.43-.595.06-.023.136-.033.194-.033.195 0 .375.104.495.254l2.462 3.33V8.108c0-.345.282-.63.63-.63.345 0 .63.285.63.63v4.771zm-5.741 0c0 .344-.282.629-.631.629-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.627-.63.349 0 .631.285.631.63v4.771zm-2.466.629H4.917c-.345 0-.63-.285-.63-.629V8.108c0-.345.285-.63.63-.63.348 0 .63.285.63.63v4.141h1.756c.348 0 .629.283.629.63 0 .344-.281.629-.629.629M24 10.314C24 4.943 18.615.572 12 .572S0 4.943 0 10.314c0 4.811 4.27 8.842 10.035 9.608.391.082.923.258 1.058.59.12.301.079.766.038 1.08l-.164 1.02c-.045.301-.24 1.186 1.049.645 1.291-.539 6.916-4.078 9.436-6.975C23.176 14.393 24 12.458 24 10.314" />
            </svg>
            <div className="min-w-0">
              <div className="text-sm font-bold text-[#06c755]">{spot.region.areaName}エリアの最新釣果をLINEでお届け</div>
              <div className="text-xs text-muted-foreground">友だち追加で釣果速報・潮汐情報を受け取る</div>
            </div>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="ml-auto h-4 w-4 flex-shrink-0 text-[#06c755]" aria-hidden="true">
              <path d="M9 18l6-6-6-6" />
            </svg>
          </a>
          <section>
            <h3 className="mb-3 text-lg font-bold">ボウズ確率</h3>
            <SpotBouzuCard spotType={spot.spotType} difficulty={spot.difficulty} rating={spot.rating} reviewCount={spot.reviewCount} prefecture={spot.region.prefecture} areaName={spot.region.areaName} isFree={spot.isFree} hasRentalRod={spot.hasRentalRod} catchableFishCount={spot.catchableFish.length} catchableFishDetails={spot.catchableFish.map((cf) => ({ fishSlug: cf.fish.slug, fishName: cf.fish.name, method: cf.method, catchDifficulty: cf.catchDifficulty, monthStart: cf.monthStart, monthEnd: cf.monthEnd, peakSeason: cf.peakSeason }))} />
          </section>
          {spot.youtubeLinks && spot.youtubeLinks.length > 0 && (
            <section>
              <h3 className="mb-4 flex items-center gap-2 text-lg font-bold"><Play className="size-5" />参考動画</h3>
              <p className="mb-4 text-sm text-muted-foreground">このスポットでの釣りの様子がわかるYouTube動画です。</p>
              <YouTubeVideoList links={spot.youtubeLinks} />
            </section>
          )}
          {(() => {
            const methods = spot.catchableFish.map((cf) => cf.method);
            const methodVideos = methods.length > 0
              ? getVideosForMethods(methods, 2)
              : getVideosForSpotType(spot.spotType, 2);
            return methodVideos.length > 0 ? (
              <YouTubeEmbedList
                videos={methodVideos}
                sectionTitle="関連する釣り方動画"
                description={`${spot.name}で使える釣り方の解説動画です。`}
              />
            ) : null;
          })()}
        </>}
        fishTab={<>
          <h2 className="sr-only">{spot.name}の釣り情報</h2>
          <section>
            <h3 className="mb-3 flex items-center gap-2 text-lg font-bold"><Fish className="size-5" />{spot.name}で釣れる魚の季節カレンダー</h3>
            {spot.catchableFish.length > 0 ? (
              <Card className="py-3 sm:py-4"><CardContent className="px-3 sm:px-4 overflow-x-auto scrollbar-hide"><div className="min-w-[480px]"><SeasonCalendar catchableFish={spot.catchableFish} /></div></CardContent></Card>
            ) : (<p className="text-sm text-muted-foreground">釣れる魚の情報はまだ登録されていません。</p>)}
          </section>
          {spot.catchableFish.length > 0 && (
            <section>
              <h3 className="mb-3 text-lg font-bold">魚種別の釣り方</h3>
              <div className="space-y-2">
                {spot.catchableFish.map((cf, idx) => {
                  const methodExplanation = explainMethod(cf.method);
                  return (
                    <div key={`${cf.fish.id}-${cf.method}-${idx}`} className="rounded-lg border p-3 text-sm">
                      <div className="flex items-center justify-between gap-2">
                        <div className="flex items-center gap-2 min-w-0">
                          <Link href={`/fish/${cf.fish.slug}`} className="font-medium truncate hover:text-primary hover:underline">{cf.fish.name}</Link>
                          <Badge variant="secondary" className="text-xs shrink-0">{cf.method}</Badge>
                        </div>
                        <p className="text-xs text-muted-foreground shrink-0">{explainTime(cf.recommendedTime)}</p>
                      </div>
                      {methodExplanation && (<p className="mt-1.5 text-xs text-muted-foreground"><span className="mr-1">💡</span>{cf.method}とは… {methodExplanation}</p>)}
                      {/* source フィールドはUI非表示（内部管理用に残す） */}
                      <div className="mt-2"><FishLikeButton spotSlug={slug} fishSlug={cf.fish.slug} /></div>
                    </div>
                  );
                })}
              </div>
            </section>
          )}
          {/* 県×魚種プログラマティックページへのリンク */}
          {spot.catchableFish.length > 0 && (() => {
            const pref = getPrefectureByName(spot.region.prefecture);
            if (!pref) return null;
            const seen = new Set<string>();
            const uniqueFish = spot.catchableFish.filter(cf => {
              if (seen.has(cf.fish.slug)) return false;
              seen.add(cf.fish.slug);
              return true;
            });
            return (
              <section>
                <h3 className="mb-2 text-sm font-bold">{pref.name}で釣れる魚のスポットをもっと見る</h3>
                <div className="flex flex-wrap gap-1.5">
                  {uniqueFish.map(cf => (
                    <Link key={cf.fish.slug} href={`/prefecture/${pref.slug}/fish/${cf.fish.slug}`}>
                      <Badge variant="outline" className="text-xs cursor-pointer hover:bg-primary hover:text-white transition-colors">
                        {cf.fish.name}
                      </Badge>
                    </Link>
                  ))}
                </div>
              </section>
            );
          })()}
          {(spot.mazumeInfo || spot.tideAdvice) && (
            <section>
              <h3 className="mb-4 flex items-center gap-2 text-lg font-bold"><Compass className="size-5" />マヅメ・潮汐ガイド</h3>
              <TideMazumeInfo tideAdvice={spot.tideAdvice} mazumeInfo={spot.mazumeInfo} />
            </section>
          )}
          {spot.catchableFish.length > 0 && (
            <section><FishingReportSummary spotSlug={slug} fishList={spot.catchableFish.map((cf) => ({ slug: cf.fish.slug, name: cf.fish.name }))} /></section>
          )}
        </>}
        gearTab={<>
          <h2 className="sr-only">おすすめの仕掛け・装備</h2>
          {spot.tackleRecommendations.filter((t) => t.amazonUrl !== "#" && t.rakutenUrl !== "#").length > 0 && (
            <section>
              <h3 className="mb-4 text-lg font-bold">{spot.name}で使える仕掛け・タックル</h3>
              <div className="space-y-4">{spot.tackleRecommendations.filter((t) => t.amazonUrl !== "#" && t.rakutenUrl !== "#").map((tackle) => (<TackleCard key={tackle.id} tackle={tackle} />))}</div>
              <p className="mt-3 text-xs text-muted-foreground">※ 上記リンクはアフィリエイトリンクを含みます。購入による追加費用は発生しません。</p>
            </section>
          )}
          {spot.gearGuides && spot.gearGuides.length > 0 && (
            <section>
              <h3 className="mb-4 flex items-center gap-2 text-lg font-bold"><Wrench className="size-5" />初心者向け装備ガイド</h3>
              <p className="mb-4 text-sm text-muted-foreground">このスポットでの釣りに必要な道具をわかりやすくまとめました。</p>
              <GearGuideList guides={spot.gearGuides} />
            </section>
          )}
          {spot.catchableFish.length > 0 && (
            <section>
              <h3 className="mb-4 flex items-center gap-2 text-lg font-bold"><Wrench className="size-5" />{spot.gearGuides && spot.gearGuides.length > 0 ? "おすすめ装備" : "この釣り場でおすすめの装備"}</h3>
              <p className="mb-2 text-sm text-muted-foreground">このスポットの釣り方に合った装備をピックアップしました。</p>
              <SpotAffiliateRecommend methods={spot.catchableFish.map((cf) => cf.method)} isNightFishing={isNightFishing} prefecture={spot.region.prefecture} />
            </section>
          )}
          <section>
            <h3 className="mb-4 flex items-center gap-2 text-lg font-bold"><ShoppingBag className="size-5" />持ち物チェックリスト</h3>
            <PackingChecklist spotType={spot.spotType} hasConvenienceStore={spot.hasConvenienceStore} hasToilet={spot.hasToilet} hasFishingShop={spot.hasFishingShop} hasRentalRod={spot.hasRentalRod} difficulty={spot.difficulty} safetyLevel={spot.safetyLevel} isNightFishing={isNightFishing} />
          </section>
        </>}
        accessTab={<>
          <h2 className="sr-only">アクセス・現地情報</h2>
          <section>
            <h3 className="mb-4 text-lg font-bold">アクセス情報</h3>
            <Card className="py-4">
              <CardHeader className="px-4 pb-0 pt-0"><CardTitle className="text-base"><MapPin className="mr-1 inline size-4" />所在地</CardTitle></CardHeader>
              <CardContent className="space-y-4 px-4">
                <div>
                  <p className="text-sm font-medium">{spot.address}</p>
                  <div className="mt-2 flex flex-wrap gap-2">
                    <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(spot.name)}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm transition-colors hover:bg-blue-700 min-h-[40px]"><MapPin className="size-4" />Google Mapで場所を確認</a>
                    <a href={`https://www.google.com/maps/dir/?api=1&destination=${spot.latitude},${spot.longitude}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 rounded-lg border border-blue-200 bg-blue-50 px-4 py-2 text-sm font-medium text-blue-700 transition-colors hover:bg-blue-100 min-h-[40px]"><Navigation2 className="size-4" />ルート案内</a>
                  </div>
                </div>
                <Separator />
                <div>
                  <h4 className="mb-1 text-sm font-medium"><Car className="mr-1 inline size-4" />アクセス方法</h4>
                  <p className="text-sm text-muted-foreground">{spot.accessInfo}</p>
                </div>
                <Separator />
                <ParkingGuideCard parkingGuide={spot.parkingGuide} hasParking={spot.hasParking} parkingDetail={spot.parkingDetail} spotName={spot.name} spotLatitude={spot.latitude} spotLongitude={spot.longitude} />
                <Separator />
                <div className="rounded-lg border border-sky-200 bg-sky-50 p-3">
                  <h4 className="mb-1 text-sm font-semibold text-sky-800"><Car className="mr-1 inline size-4" />レンタカーで行く</h4>
                  <p className="mb-2 text-xs text-sky-700">{spot.name}は車でのアクセスが便利です。周辺のレンタカーを比較・予約できます。</p>
                  <a
                    href="https://a.r10.to/hFFHZ3"
                    target="_blank"
                    rel="noopener noreferrer sponsored"
                    className="inline-flex items-center gap-1 rounded-md bg-sky-600 px-3 py-1.5 text-xs font-medium text-white transition-colors hover:bg-sky-700"
                  >
                    <Navigation2 className="size-3.5" />
                    楽天レンタカーで探す
                    <ExternalLink className="size-3" />
                  </a>
                </div>
              </CardContent>
            </Card>
          </section>
          <section>
            <h3 className="mb-4 text-lg font-bold">現地の様子（ストリートビュー）</h3>
            <StreetViewSection latitude={spot.latitude} longitude={spot.longitude} spotName={spot.name} address={spot.address} />
          </section>
          {spot.structureTypes && spot.structureTypes.length > 0 && (
            <SatelliteAnalysisSection
              structureTypes={spot.structureTypes}
              spotName={spot.name}
              spotType={spot.spotType}
            />
          )}
          {nearbyShopsWithDist.length > 0 && (
            <section>
              <h3 className="mb-3 text-lg font-bold">近くの釣具店</h3>
              <div className="grid gap-3 sm:grid-cols-2">
                {nearbyShopsWithDist.map(({ shop, distanceKm: dist }) => (
                  <Link key={shop.id} href={`/shops/${shop.slug}`}>
                    <Card className="group h-full gap-0 py-0 transition-shadow hover:shadow-md"><CardContent className="p-4">
                      <div className="flex items-start justify-between gap-2">
                        <h3 className="truncate font-semibold group-hover:text-primary">{shop.name}</h3>
                        <span className="shrink-0 rounded-full bg-muted px-2 py-0.5 text-xs font-medium text-muted-foreground">
                          {dist < 1 ? `${Math.round(dist * 1000)}m` : `${dist.toFixed(1)}km`}
                        </span>
                      </div>
                      <div className="mt-1 flex items-center gap-1.5">
                        <p className="text-xs text-muted-foreground line-clamp-1">{shop.address}</p>
                        <a href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(shop.address)}`} target="_blank" rel="noopener noreferrer" className="relative z-10 shrink-0 text-[10px] text-primary hover:underline">ナビ</a>
                      </div>
                      <p className="mt-0.5 text-xs text-muted-foreground">{shop.businessHours}</p>
                      <div className="mt-2 flex flex-wrap gap-1">
                        {shop.hasLiveBait && <Badge variant="outline" className="text-[10px] px-1.5 py-0">活きエサ</Badge>}
                        {shop.hasFrozenBait && <Badge variant="outline" className="text-[10px] px-1.5 py-0">冷凍エサ</Badge>}
                        {shop.hasRentalRod && <Badge variant="outline" className="text-[10px] px-1.5 py-0">レンタル竿</Badge>}
                        {shop.hasParking && <Badge variant="outline" className="text-[10px] px-1.5 py-0">駐車場</Badge>}
                      </div>
                    </CardContent></Card>
                  </Link>
                ))}
              </div>
              <p className="mt-2 text-right text-xs text-muted-foreground">
                <Link href="/shops" className="text-primary hover:underline">全国の釣具店を探す →</Link>
              </p>
            </section>
          )}
          <NearbyAccommodation
            spotName={spot.name}
            latitude={spot.latitude}
            longitude={spot.longitude}
            prefecture={spot.region.prefecture}
            areaName={spot.region.areaName}
          />
        </>}
      />

      {/* 広告 */}
      <InArticleAd className="mt-6" />

      {/* この釣り場で使える釣り方ガイド（常時表示） */}
      {(() => {
        const METHOD_GUIDE_MAP: Record<string, { href: string; label: string; desc: string }> = {
          "サビキ釣り": { href: "/guide/sabiki", label: "サビキ釣り完全ガイド", desc: "仕掛け・コマセの使い方を初心者向けに図解" },
          "ちょい投げ": { href: "/guide/choinage", label: "ちょい投げ完全ガイド", desc: "キスやハゼを狙う投げ釣り入門" },
          "ちょい投げ釣り": { href: "/guide/choinage", label: "ちょい投げ完全ガイド", desc: "キスやハゼを狙う投げ釣り入門" },
          "エギング": { href: "/guide/eging", label: "エギング完全ガイド", desc: "エギの選び方とシャクリ方を解説" },
          "ショアジギング": { href: "/guide/jigging", label: "ショアジギング完全ガイド", desc: "メタルジグで青物を狙う方法" },
          "ウキ釣り": { href: "/guide/float-fishing", label: "ウキ釣り完全ガイド", desc: "ウキの種類・タナの取り方を解説" },
          "穴釣り": { href: "/guide/anazuri", label: "穴釣り完全ガイド", desc: "テトラの隙間でカサゴ・メバルを狙う" },
          "ルアー釣り": { href: "/guide/lure", label: "ルアー釣り完全ガイド", desc: "シーバスやヒラメをルアーで狙う" },
          "泳がせ釣り": { href: "/guide/oyogase", label: "泳がせ釣り入門ガイド", desc: "活きエサで大物を狙う泳がせ釣り" },
          "遠投カゴ釣り": { href: "/guide/entou-kago", label: "遠投カゴ釣りガイド", desc: "沖のタナを攻めるカゴ釣り" },
          "投げ釣り": { href: "/guide/choinage", label: "ちょい投げ完全ガイド", desc: "投げ釣りの基本とコツ" },
          "フカセ釣り": { href: "/guide/float-fishing", label: "ウキ釣り完全ガイド", desc: "フカセ釣りの基本テクニック" },
        };
        const methods = new Set(spot.catchableFish.map((cf) => cf.method));
        const seenHref = new Set<string>();
        const guides = Array.from(methods)
          .map((m) => METHOD_GUIDE_MAP[m])
          .filter((g): g is { href: string; label: string; desc: string } => {
            if (!g || seenHref.has(g.href)) return false;
            seenHref.add(g.href);
            return true;
          });
        if (guides.length === 0) return null;
        return (
          <section className="mt-8 sm:mt-12">
            <h2 className="mb-4 flex items-center gap-2 text-lg font-bold sm:text-xl">
              <BookOpen className="size-5 text-primary" />
              {spot.name}で使える釣り方ガイド
            </h2>
            <p className="mb-4 text-sm text-muted-foreground">
              {spot.name}で実践できる釣り方を詳しく解説しています。初心者の方は仕掛けの準備から学べます。
            </p>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {guides.map((guide) => (
                <Link key={guide.href} href={guide.href}>
                  <Card className="group h-full gap-0 py-0 transition-shadow hover:shadow-md">
                    <CardContent className="p-4">
                      <h3 className="text-sm font-semibold group-hover:text-primary">{guide.label}</h3>
                      <p className="mt-1 text-xs text-muted-foreground">{guide.desc}</p>
                    </CardContent>
                  </Card>
                </Link>
              ))}
            </div>
            <div className="mt-3 flex flex-wrap gap-2">
              <Link href="/guide" className="text-sm text-primary hover:underline">
                すべての釣り方ガイドを見る →
              </Link>
              {isNightFishing && (
                <Link href="/guide/night-fishing" className="text-sm text-primary hover:underline">
                  ナイトフィッシングガイド →
                </Link>
              )}
              <Link href="/guide/knots" className="text-sm text-primary hover:underline">
                結び方ガイド →
              </Link>
            </div>
          </section>
        );
      })()}

      {/* この釣り場のポイント（固有コンテンツ） */}
      {(() => {
        const spotTips = generateSpotTips(spot);
        if (spotTips.length === 0) return null;
        return (
          <section className="mt-8 sm:mt-12">
            <h2 className="mb-4 flex items-center gap-2 text-lg font-bold sm:text-xl">
              <Star className="size-5 text-amber-500" />
              {spot.name}のポイント
            </h2>
            <Card className="gap-0 py-0">
              <CardContent className="p-4 sm:p-5">
                <ul className="space-y-3">
                  {spotTips.map((tip, idx) => (
                    <li key={idx} className="flex gap-3">
                      <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-amber-100 text-xs font-bold text-amber-700">
                        {idx + 1}
                      </span>
                      <span className="text-sm leading-relaxed text-muted-foreground">{tip}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </section>
        );
      })()}

      {/* この釣り場の攻略法 */}
      {spot.catchableFish.length > 0 && (() => {
        // ベストシーズン算出
        const monthCountsForStrategy = Array.from({ length: 12 }, (_, i) => {
          const m = i + 1;
          return {
            month: m,
            count: spot.catchableFish.filter(cf => {
              if (cf.monthStart <= cf.monthEnd) return m >= cf.monthStart && m <= cf.monthEnd;
              return m >= cf.monthStart || m <= cf.monthEnd;
            }).length,
          };
        });
        const maxCountStrategy = Math.max(...monthCountsForStrategy.map(mc => mc.count));
        const bestMonthsStrategy = monthCountsForStrategy.filter(mc => mc.count === maxCountStrategy).map(mc => monthNames[mc.month]);

        // おすすめ釣り方トップ3（重複排除）
        const seenMethodsStrategy = new Set<string>();
        const topMethods = spot.catchableFish
          .filter(cf => {
            if (seenMethodsStrategy.has(cf.method)) return false;
            seenMethodsStrategy.add(cf.method);
            return true;
          })
          .slice(0, 3);

        // 釣り方ガイドのリンクマップ
        const METHOD_STRATEGY_MAP: Record<string, string> = {
          "サビキ釣り": "/guide/sabiki",
          "ちょい投げ": "/guide/choinage",
          "ちょい投げ釣り": "/guide/choinage",
          "エギング": "/guide/eging",
          "ショアジギング": "/guide/jigging",
          "ウキ釣り": "/guide/float-fishing",
          "穴釣り": "/guide/anazuri",
          "ルアー釣り": "/guide/lure",
          "泳がせ釣り": "/guide/oyogase",
          "遠投カゴ釣り": "/guide/entou-kago",
          "投げ釣り": "/guide/choinage",
          "フカセ釣り": "/guide/float-fishing",
        };

        // 釣り方の説明マップ
        const METHOD_BRIEF: Record<string, string> = {
          "サビキ釣り": "コマセで魚を寄せて数釣りできる初心者向けの釣り方",
          "ちょい投げ": "仕掛けを軽く投げて砂底の魚を狙う手軽な釣り方",
          "ちょい投げ釣り": "仕掛けを軽く投げて砂底の魚を狙う手軽な釣り方",
          "エギング": "エギ（疑似餌）でイカを狙うゲーム性の高い釣り方",
          "ショアジギング": "メタルジグを遠投して青物を狙うダイナミックな釣り方",
          "ウキ釣り": "ウキで仕掛けを一定の深さに漂わせて多彩な魚種を狙う釣り方",
          "穴釣り": "テトラポッドの隙間に仕掛けを落として根魚を狙う釣り方",
          "ルアー釣り": "疑似餌で魚の捕食本能を刺激して釣るアクティブな釣り方",
          "泳がせ釣り": "小魚を活きエサにして大物を狙う釣り方",
          "遠投カゴ釣り": "カゴにコマセを詰めて沖のポイントを攻める釣り方",
          "投げ釣り": "オモリと仕掛けを遠投して底物を狙う釣り方",
          "フカセ釣り": "コマセを撒いてウキ仕掛けで自然に流す繊細な釣り方",
        };

        // 季節別アドバイス
        const seasonDetails = generateSeasonDetail(spot);

        return (
          <section className="mt-8 sm:mt-12">
            <h2 className="mb-4 flex items-center gap-2 text-lg font-bold sm:text-xl">
              <Compass className="size-5 text-primary" />
              {spot.name}の攻略法
            </h2>
            <Card className="gap-0 py-0">
              <CardContent className="space-y-5 p-4 sm:p-5">
                {/* 狙い目の時間帯（スポット固有アドバイス） */}
                <div>
                  <h3 className="mb-1.5 text-sm font-bold">狙い目の時間帯</h3>
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    {generateTimeAdvice(spot)}
                  </p>
                </div>
                {/* ベストシーズン */}
                <div>
                  <h3 className="mb-1.5 text-sm font-bold">ベストシーズン</h3>
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    {spot.name}の最も魚種が豊富な時期は<strong>{bestMonthsStrategy.slice(0, 3).join("・")}</strong>頃です（最大{maxCountStrategy}種類が狙えます）。
                    {spot.catchableFish.filter(cf => cf.peakSeason).length > 0 &&
                      `旬の魚: ${spot.catchableFish.filter(cf => cf.peakSeason).slice(0, 3).map(cf => `${cf.fish.name}（${monthNames[cf.monthStart]}〜${monthNames[cf.monthEnd]}）`).join("、")}。`}
                  </p>
                </div>
                {/* 季節別の詳細アドバイス */}
                {seasonDetails.length > 0 && (
                  <div>
                    <h3 className="mb-2 text-sm font-bold">季節ごとの釣りもの</h3>
                    <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
                      {seasonDetails.map(sd => (
                        <div key={sd.season} className="rounded-lg border bg-muted/30 p-3">
                          <p className="text-xs font-bold text-primary">{sd.season}</p>
                          <p className="mt-0.5 text-xs font-medium">{sd.fish}</p>
                          <p className="mt-1 text-xs text-muted-foreground">{sd.advice}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
                {/* おすすめ釣り方トップ3（文脈別説明） */}
                <div>
                  <h3 className="mb-2 text-sm font-bold">おすすめの釣り方</h3>
                  <div className="space-y-2">
                    {topMethods.map((cf, idx) => {
                      const guideHref = METHOD_STRATEGY_MAP[cf.method];
                      const brief = generateContextMethodBrief(cf.method, spot);
                      const targetFish = spot.catchableFish.filter(f => f.method === cf.method).slice(0, 3).map(f => f.fish.name).join("・");
                      return (
                        <div key={cf.fish.id + cf.method} className="rounded-lg border bg-muted/30 p-3">
                          <div className="flex items-center gap-2">
                            <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">{idx + 1}</span>
                            <span className="text-sm font-bold">{cf.method}</span>
                            {guideHref && (
                              <Link href={guideHref} className="ml-auto text-xs text-primary hover:underline">
                                ガイドを見る →
                              </Link>
                            )}
                          </div>
                          <p className="mt-1 text-xs text-muted-foreground">{brief}</p>
                          <p className="mt-0.5 text-xs text-muted-foreground">対象魚: {targetFish}</p>
                        </div>
                      );
                    })}
                  </div>
                </div>
                {/* 関連ガイドリンク */}
                <div className="flex flex-wrap gap-2 border-t pt-3">
                  <Link href="/guide" className="text-xs text-primary hover:underline">すべての釣り方ガイド →</Link>
                  <Link href="/fishing-calendar" className="text-xs text-primary hover:underline">月別釣りカレンダー →</Link>
                  {spot.difficulty === "beginner" && (
                    <Link href="/for-beginners" className="text-xs text-primary hover:underline">釣りの始め方ガイド →</Link>
                  )}
                </div>
              </CardContent>
            </Card>
          </section>
        );
      })()}

      {/* 関連スポット・記事 */}
      <h2 className="mt-8 text-xl font-bold sm:mt-12 sm:text-2xl">関連スポット・記事</h2>

      {/* この近くの釣り場 */}
      {nearbySpots.length > 0 && (
        <section id="nearby-spots" className="mt-6 sm:mt-8">
          <h3 className="mb-3 flex items-center gap-2 text-base font-bold sm:mb-4 sm:text-lg">
            <MapPin className="size-5" />
            {spot.name}周辺の釣りスポット
          </h3>
          <div className="flex gap-3 overflow-x-auto pb-2">
            {nearbySpots.map((nearSpot) => {
              const nearSpotTypeLabel = SPOT_TYPE_LABELS[nearSpot.spotType];
              const nearSpotFishStr = nearSpot.fishNames.slice(0, 2).join("・");
              const nearSpotRichLabel = nearSpotFishStr
                ? `${nearSpot.name}（${nearSpot.prefecture}の${nearSpotFishStr}釣り場）`
                : `${nearSpot.name}（${nearSpot.prefecture}の${nearSpotTypeLabel}）`;
              return (
              <Link
                key={nearSpot.id}
                href={`/spots/${nearSpot.slug}`}
                className="shrink-0"
                title={nearSpotRichLabel}
                aria-label={nearSpotRichLabel}
              >
                <div className="min-w-[220px] rounded-lg border bg-white p-4 transition-shadow hover:shadow-md">
                  <p className="text-sm text-gray-500 mb-1">
                    約{nearSpot.distanceKm < 10
                      ? nearSpot.distanceKm.toFixed(1)
                      : Math.round(nearSpot.distanceKm).toString()}km
                  </p>
                  <p className="font-medium text-blue-600 hover:underline leading-snug">
                    {nearSpot.name}
                  </p>
                  <p className="mt-0.5 text-xs text-gray-500">
                    {nearSpot.prefecture}の{nearSpotTypeLabel}
                    {nearSpotFishStr ? ` | ${nearSpotFishStr}` : ""}
                  </p>
                  {nearSpot.fishNames.length > 0 && (
                    <p className="mt-1.5 text-xs text-muted-foreground">
                      釣れる魚: {nearSpot.fishNames.join("・")}
                    </p>
                  )}
                </div>
              </Link>
              );
            })}
          </div>
          <NearbyGpsSearch spots={gpsNearbyData} currentSpotSlug={slug} />
        </section>
      )}

      {/* 関連スポット・ガイド（折りたたみ） */}
      <CollapsibleSection
        title={`${spot.region.prefecture}の関連スポット・ガイド`}
        icon={<Compass className="size-5 text-primary" />}
        previewText="タップして表示"
      >
        {/* 同じ都道府県の釣りスポット */}
        {(() => {
          const samePrefSpots = getSpotsByPrefecture(spot.region.prefecture, spot.slug, 6)
            .map((ps) => ({
              id: ps.id,
              slug: ps.slug,
              name: ps.name,
              spotType: ps.spotType,
              areaName: ps.region.areaName,
              rating: ps.rating,
              fishNames: ps.catchableFish?.slice(0, 2).map((cf) => cf.fish.name) || [],
            }));
          if (samePrefSpots.length === 0) return null;
          const pref = getPrefectureByName(spot.region.prefecture);
          return (
            <div className="mb-6">
              <h3 className="mb-3 text-sm font-bold">{spot.region.prefecture}の他の釣りスポット</h3>
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {samePrefSpots.map((ps) => {
                  const psFishStr = ps.fishNames.join("・");
                  const psTypeLabel = SPOT_TYPE_LABELS[ps.spotType] || "";
                  return (
                  <Link key={ps.id} href={`/spots/${ps.slug}`} title={psFishStr ? `${ps.name}（${psFishStr}が釣れる${psTypeLabel}）` : `${ps.name}（${spot.region.prefecture}の${psTypeLabel}）`}>
                    <Card className="group h-full gap-0 py-0 transition-shadow hover:shadow-md">
                      <CardContent className="p-3">
                        <h4 className="text-sm font-semibold group-hover:text-primary truncate">{ps.name}</h4>
                        <p className="mt-0.5 text-xs text-muted-foreground">{ps.areaName} - {psTypeLabel}</p>
                        {psFishStr && <p className="mt-0.5 text-xs text-muted-foreground">{psFishStr}が狙える</p>}
                        <div className="mt-1 flex items-center gap-1 text-xs">
                          <Star className="size-3 fill-yellow-400 text-yellow-400" />
                          <span>{ps.rating.toFixed(1)}</span>
                        </div>
                      </CardContent>
                    </Card>
                  </Link>
                  );
                })}
              </div>
              {pref && (
                <div className="mt-2 text-right">
                  <Link href={`/prefecture/${pref.slug}`} className="text-sm text-primary hover:underline">
                    {spot.region.prefecture}の釣りスポットをすべて見る →
                  </Link>
                </div>
              )}
            </div>
          );
        })()}

        {/* 魚種リンク */}
        {spot.catchableFish.length > 0 && (
          <div className="mb-6">
            <h3 className="mb-2 text-sm font-bold">狙える魚種</h3>
            <div className="flex flex-wrap gap-1.5">
              {(() => {
                const seen = new Set<string>();
                return spot.catchableFish.filter(cf => { if (seen.has(cf.fish.slug)) return false; seen.add(cf.fish.slug); return true; }).map((cf) => (
                  <Link key={cf.fish.id} href={`/fish/${cf.fish.slug}`}>
                    <Badge variant="outline" className="cursor-pointer px-2 py-1 text-xs transition-colors hover:bg-primary hover:text-primary-foreground">
                      {cf.fish.name}
                    </Badge>
                  </Link>
                ));
              })()}
            </div>
          </div>
        )}

        {/* 釣り方ガイド */}
        {(() => {
          const METHOD_TO_GUIDE: Record<string, { href: string; label: string }> = {
            "サビキ釣り": { href: "/guide/sabiki", label: "サビキ釣り完全ガイド" },
            "ちょい投げ": { href: "/guide/choinage", label: "ちょい投げ完全ガイド" },
            "ちょい投げ釣り": { href: "/guide/choinage", label: "ちょい投げ完全ガイド" },
            "エギング": { href: "/guide/eging", label: "エギング完全ガイド" },
            "ショアジギング": { href: "/guide/jigging", label: "ショアジギング完全ガイド" },
            "ウキ釣り": { href: "/guide/float-fishing", label: "ウキ釣り完全ガイド" },
            "穴釣り": { href: "/guide/anazuri", label: "穴釣り完全ガイド" },
            "ルアー釣り": { href: "/guide/lure", label: "ルアー釣り完全ガイド" },
            "泳がせ釣り": { href: "/guide/oyogase", label: "泳がせ釣り入門ガイド" },
            "遠投カゴ釣り": { href: "/guide/entou-kago", label: "遠投カゴ釣りガイド" },
            "投げ釣り": { href: "/guide/choinage", label: "ちょい投げ完全ガイド" },
          };
          const methods = new Set(spot.catchableFish.map((cf) => cf.method));
          const seen = new Set<string>();
          const uniqueGuides = Array.from(methods)
            .map((m) => METHOD_TO_GUIDE[m])
            .filter((g): g is { href: string; label: string } => {
              if (!g || seen.has(g.href)) return false;
              seen.add(g.href);
              return true;
            });
          if (uniqueGuides.length === 0) return null;
          return (
            <div className="mb-6">
              <h3 className="mb-2 text-sm font-bold">おすすめ釣り方ガイド</h3>
              <div className="flex flex-wrap gap-1.5">
                {uniqueGuides.slice(0, 4).map((guide) => (
                  <Link key={guide.href} href={guide.href}>
                    <Badge variant="outline" className="cursor-pointer px-2 py-1 text-xs transition-colors hover:bg-primary hover:text-primary-foreground">
                      {guide.label}
                    </Badge>
                  </Link>
                ))}
              </div>
            </div>
          );
        })()}

        {/* 都道府県ガイドリンク */}
        {(() => {
          const pref = getPrefectureByName(spot.region.prefecture);
          if (!pref) return null;
          return (
            <div className="mb-4">
              <h3 className="mb-2 text-sm font-bold">{spot.region.prefecture}の釣り情報</h3>
              <div className="flex flex-wrap gap-1.5">
                <Link href={`/prefecture/${pref.slug}`}>
                  <Badge variant="outline" className="cursor-pointer px-2 py-1 text-xs transition-colors hover:bg-primary hover:text-primary-foreground">
                    {spot.region.prefecture}の釣りガイド
                  </Badge>
                </Link>
                <Link href={`/fishing-rules/${pref.slug}`}>
                  <Badge variant="outline" className="cursor-pointer px-2 py-1 text-xs transition-colors hover:bg-primary hover:text-primary-foreground">
                    {spot.region.prefecture}の釣りルール
                  </Badge>
                </Link>
              </div>
            </div>
          );
        })()}
      </CollapsibleSection>

      {/* よくある質問（FAQ） */}
      <section className="mt-6 sm:mt-8">
        <h3 className="mb-4 flex items-center gap-2 text-lg font-bold">
          <HelpCircle className="size-5 text-primary" />
          {spot.name}のよくある質問
        </h3>
        <div className="space-y-3">
          {faqJsonLd.mainEntity.slice(0, 6).map((q: { name: string; acceptedAnswer: { text: string } }, i: number) => (
            <Card key={i} className="gap-0 py-0">
              <CardContent className="p-4">
                <h3 className="mb-2 text-sm font-bold">
                  Q. {q.name}
                </h3>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  {q.acceptedAnswer.text}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* 都道府県ガイド・地域ガイドは上の折りたたみセクションに統合済み */}

      {/* 関連コラム（ブログ記事への内部リンク — AdSense対策） */}
      {(() => {
        const relatedPosts = getRelatedBlogPostsForSpot({
          prefecture: spot.region.prefecture,
          areaName: spot.region.areaName,
          spotType: spot.spotType,
          methods: [...new Set(spot.catchableFish.map((cf) => cf.method))],
          fishNames: spot.catchableFish.slice(0, 8).map((cf) => cf.fish.name),
          currentMonth,
        });
        if (relatedPosts.length === 0) return null;
        return (
          <section className="mt-6 sm:mt-8">
            <h3 className="mb-4 flex items-center gap-2 text-lg font-bold">
              <FileText className="size-5 text-primary" />
              関連コラム・釣り方ガイド
            </h3>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {relatedPosts.slice(0, 5).map((post) => (
                <Link key={post.slug} href={`/blog/${post.slug}`} className="group">
                  <Card className="h-full gap-0 py-0 transition-colors group-hover:border-primary/40 group-hover:bg-primary/5">
                    <CardContent className="p-4">
                      <Badge variant="secondary" className="mb-2 text-[10px]">
                        {BLOG_CATEGORIES[post.category]}
                      </Badge>
                      <h4 className="mb-1.5 text-sm font-bold leading-snug line-clamp-2 group-hover:text-primary">
                        {post.title}
                      </h4>
                      <p className="text-xs leading-relaxed text-muted-foreground line-clamp-2">
                        {post.description.slice(0, 80)}
                        {post.description.length > 80 ? "..." : ""}
                      </p>
                    </CardContent>
                  </Card>
                </Link>
              ))}
            </div>
            <div className="mt-3 text-right">
              <Link
                href="/blog"
                className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline"
              >
                <BookOpen className="size-3" />
                コラム一覧を見る
              </Link>
            </div>
          </section>
        );
      })()}

      {/* まとめ（GEO最適化：AI引用しやすい要約 — スポット固有サマリー） */}
      {(() => {
        const summary = generateSpotSummary(spot);
        return (
          <section className="mt-8 sm:mt-12 spot-description">
            <h3 className="mb-3 text-base font-bold sm:text-lg">{spot.name}の釣り情報まとめ</h3>
            <Card className="gap-0 py-0">
              <CardContent className="p-4">
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-primary">✓</span>
                    <span>{summary.oneLineFeature}</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-primary">✓</span>
                    <span>{summary.topFishAndSeason}</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-primary">✓</span>
                    <span>{summary.recommendedMethod}</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-primary">✓</span>
                    <span>{summary.facilityOverview}</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="mt-0.5 text-primary">✓</span>
                    <span>{summary.difficultyComment}</span>
                  </li>
                </ul>
                <p className="mt-3 text-xs text-muted-foreground">
                  所在地: {spot.address}。{spot.accessInfo}
                </p>
                {/* まとめ内の内部リンク */}
                <div className="mt-4 flex flex-wrap gap-2">
                  {(() => {
                    const pref = getPrefectureByName(spot.region.prefecture);
                    if (!pref) return null;
                    return (
                      <>
                        <Link href={`/prefecture/${pref.slug}`} className="inline-flex items-center gap-1 rounded-md border px-2.5 py-1 text-xs font-medium text-primary transition-colors hover:bg-primary/5">
                          <MapPin className="size-3" />
                          {spot.region.prefecture}の釣りスポット一覧
                        </Link>
                        <Link href={`/fishing-rules/${pref.slug}`} className="inline-flex items-center gap-1 rounded-md border px-2.5 py-1 text-xs font-medium text-primary transition-colors hover:bg-primary/5">
                          <Scale className="size-3" />
                          {spot.region.prefecture}の釣りルール
                        </Link>
                      </>
                    );
                  })()}
                  <Link href={`/area/${spot.region.slug}`} className="inline-flex items-center gap-1 rounded-md border px-2.5 py-1 text-xs font-medium text-primary transition-colors hover:bg-primary/5">
                    <Compass className="size-3" />
                    {spot.region.areaName}エリアガイド
                  </Link>
                  <Link href="/fishing-calendar" className="inline-flex items-center gap-1 rounded-md border px-2.5 py-1 text-xs font-medium text-primary transition-colors hover:bg-primary/5">
                    <Fish className="size-3" />
                    月別釣りカレンダー
                  </Link>
                  <Link href="/for-beginners" className="inline-flex items-center gap-1 rounded-md border px-2.5 py-1 text-xs font-medium text-primary transition-colors hover:bg-primary/5">
                    <BookOpen className="size-3" />
                    釣りの始め方ガイド
                  </Link>
                </div>
              </CardContent>
            </Card>
          </section>
        );
      })()}

      {/* 最近見たスポット */}
      <RecentlyViewedSpots />

      {/* LINE登録バナー */}
      <section className="mt-8 sm:mt-12">
      </section>
      {spot.googleRating && (
        <p className="mt-2 text-[10px] text-muted-foreground">レビューデータ提供: Google</p>
      )}

      {/* 出典・情報源 */}
      <section className="mt-6 mb-8">
        <h2 className="mb-2 text-sm font-bold text-muted-foreground">
          出典・情報源
        </h2>
        <ul className="space-y-1 text-xs text-muted-foreground">
          <li>・釣り場情報: ツリスポ編集部調べ（{new Date().getFullYear()}年{new Date().getMonth() + 1}月時点）</li>
          <li>・座標情報: Google Maps（緯度{spot.latitude.toFixed(4)}、経度{spot.longitude.toFixed(4)}）</li>
          {spot.googleRating && <li>・レビュー評価: Google マップのクチコミ（{spot.googleReviewCount}件）に基づく</li>}
          <li>・釣れる魚情報: 公開情報および編集部調べに基づく（{spot.catchableFish.length}魚種確認）</li>
        </ul>
      </section>
    </div>
  );
}
